mipa_user_mipa_user:
    resource: "@MipaUserBundle/Resources/config/routing/user.yml"
    prefix:   /user

mipa_user_mipa_sub:
    resource: "@MipaUserBundle/Resources/config/routing/subscription.yml"
    prefix:   /subscription

mipa_user_homepage:
    path:     /hello/{name}
    defaults: { _controller: MipaUserBundle:Default:index }

mipa_user_export_csv:
  path:     /export/csv
  defaults: { _controller: MipaUserBundle:User:exportCSV }
