cron_task:
    path:     /
    defaults: { _controller: "MipaUserBundle:CronTask:index" }

cron_task_show:
    path:     /{id}/show
    defaults: { _controller: "MipaUserBundle:CronTask:show" }

cron_task_new:
    path:     /new
    defaults: { _controller: "MipaUserBundle:CronTask:new" }

cron_task_create:
    path:     /create
    defaults: { _controller: "MipaUserBundle:CronTask:create" }
    methods:  POST

cron_task_edit:
    path:     /{id}/edit
    defaults: { _controller: "MipaUserBundle:CronTask:edit" }

cron_task_update:
    path:     /{id}/update
    defaults: { _controller: "MipaUserBundle:CronTask:update" }
    methods:  [POST, PUT]

cron_task_delete:
    path:     /{id}/delete
    defaults: { _controller: "MipaUserBundle:CronTask:delete" }
    methods:  [POST, DELETE]
