Mipa\UserBundle\Entity\CronTask:
    type: entity
    table: CronTask
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 225
        commands:
            type: array
        interval:
            type: integer
        lastrun:
            type: datetime
            nullable: true