Mipa\UserBundle\Entity\Subscription:
    type: entity
    table: subscription
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        type:
            type: string
            length: 225
            unique: true
    oneToMany:
        users:
            targetEntity: User
            mappedBy: subscription
