Mipa\UserBundle\Entity\User:
    type: entity
    table: users
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 225
        gender:
            type: string
            length: 225
        address:
            type: string
            length: 225
        email:
            type: string
            length: 225
    ManyToOne:
        subscription:
            targetEntity: Subscription
            inversedBy: users
            joinColumn:
                name: subscription_id
                referencedColumnName: id
